// <auto-generated />
namespace AzureMVCWebSiteWithOAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Add_navigation_properties_to_foreignkey_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_navigation_properties_to_foreignkey_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201402151219279_Add_navigation_properties_to_foreign-key_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
